<?php
/**
 * @category    Matinict
 * @package     Matinict_CustomerOrderCashPaid
 * @copyright   Copyright (c) 2015 Abdul Matin (http://www.matinict.wordpress.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_order = $this->getOrder() ?>

<?php if(Mage::helper('customerordercancel')->canCancel($_order)): ?>
    <span class="separator">|</span>
    <a href="<?php echo $this->getUrl('customerordercancel/order/cancel', array('order_id' => $_order->getId(), '_secure'=>true)) ?>" class="link-reorder"><?php echo $this->__('Cash Paid Confirm') ?></a>
<?php endif ?>